# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e71b66d9990be8627914cda9992809acc24224b400b057c36012ca7ae936b72459aeadb42d68f8c919a0acd52c03bcab544fae4b1cf1a3d96dd42cd2724288

test:
  secret_key_base: f51f66320fb622dc0c9574401f68d03a56d2683282b7b4887abc017b206691591144db1056408beb2bd6e77300e32b251d43b596fb264994f69d5aae6daf4f78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
